export const expertiseData = [
  {
    id: 1,
    src: "/assets/services-page/expertise-1.png",
    color: "#C1EDA5",
    title: "Anxiety & Stress",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 2,
    src: "/assets/services-page/expertise-2.png",
    color: "#FFF0B0",
    title: "Parenting",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 3,
    src: "/assets/services-page/expertise-3.png",
    color: "#FFBE81",
    title: "Grief & Loss",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 4,
    src: "/assets/services-page/expertise-4.png",
    color: "#FFD5E5",
    title: "Trauma",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 5,
    src: "/assets/services-page/expertise-5.png",
    color: "#D9C2FF",
    title: "Mood & Emotion",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 6,
    src: "/assets/services-page/expertise-6.png",
    color: "#FFD5E5",
    title: "Chronic or Life",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 7,
    src: "/assets/services-page/expertise-7.png",
    color: "#FFF0B0",
    title: "Behavioral Problems",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 8,
    src: "/assets/services-page/expertise-8.png",
    color: "#C1EDA5",
    title: "Inattention",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 9,
    src: "/assets/services-page/expertise-9.png",
    color: "#FFF0B0",
    title: "Strengthening Bonds ",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 10,
    src: "/assets/services-page/expertise-10.png",
    color: "#C1EDA5",
    title: "Self-Esteem Concerns",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 11,
    src: "/assets/services-page/expertise-11.png",
    color: "#FFD5E5",
    title: "Difficulties in School",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
  {
    id: 12,
    src: "/assets/services-page/expertise-12.png",
    color: "#D9C2FF",
    title: "Adjusting to Transitions",
    text: "Offering compassionate, tailored interventions to help you process grief, ease the pain of loss, and rebuild hope",
  },
] as const;
