import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { domAnimation, LazyMotion } from "framer-motion";
import InnerLayout from "@/components/InnerLayout";




// const outfit = Outfit({

//   subsets:["latin"]
// })

const figtree = Figtree({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className}  antialiased`}
      >
         <LazyMotion features={domAnimation}>
            <InnerLayout>{children}</InnerLayout>
          </LazyMotion>
      </body>
    </html>
  );
}
